[book]
authors = ["vongdefu"]
language = "zh"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = true    # 是否折叠左侧边栏
level = 0        # the depth to start folding

