import { DefaultTheme } from "vitepress";
import { interviewSidebar } from "./sidebar/interview";
import { sourcecodeSidebar } from "./sidebar/sourcecodeSidebar";
import { websiteMaintainSidebar } from "./sidebar/websiteMaintainSidebar";

export const sidebar: DefaultTheme.Config["sidebar"] = {
  "/00-面试/": interviewSidebar,
  "/01-CS基础/": {
    base: "/01-CS基础",
    items: [
      { text: "前端", link: "/前端" },
      { text: "数据结构与算法", link: "/数据结构与算法" },
      {
        text: "计算机网络",
        base: "/01-CS基础/计算机网络",
        link: "/README",
        collapsed: false,
        items: [
          { text: "应用层", link: "/应用层" },
          { text: "传输层", link: "/传输层" },
          { text: "网络层", link: "/网络层" },
          { text: "网络接口层", link: "/网络接口层" },
          { text: "实验", link: "/实验" },
          { text: "面试题", link: "/面试题" },
        ],
      },
      {
        text: "设计模式",
        base: "/01-CS基础/设计模式",
        collapsed: false,
        items: [
          { text: "设计原则", link: "/设计原则" },
          { text: "单例", link: "/单例" },
          { text: "建造者", link: "/建造者模式" },
          { text: "策略模式", link: "/策略模式" },
          { text: "模板方法", link: "/模板方法" },
          { text: "责任链模式", link: "/责任链模式" },
        ],
      },
    ],
  },
  "/02-java/": [
    {
      text: "java基础",
      base: "/02-java/java基础",
      collapsed: false,
      items: [
        { text: "基础概念", link: "/基础概念" },
        { text: "集合", link: "/集合" },
        { text: "注解", link: "/注解" },
        { text: "泛型", link: "/泛型" },
        { text: "异常", link: "/异常" },
        { text: "IO", link: "/io" },
        { text: "Java8新特性", link: "/java8新特性" },
      ],
    },
    {
      text: "java并发编程",
      base: "/02-java/java并发编程",
      collapsed: false,
      items: [
        { text: "背景知识", link: "/背景知识" },
        {
          text: "关键字与线程本地缓存",
          base: "/02-java/java并发编程/关键字与线程本地缓存",
          items: [
            { text: "final", link: "/final" },
            { text: "synchronized", link: "/synchronized" },
            { text: "volatile", link: "/volatile" },
            { text: "ThreadLocal", link: "/ThreadLocal" },
          ],
        },
        {
          text: "线程与线程池",
          base: "/02-java/java并发编程/线程与线程池",
          link: "/README",
          items: [
            { text: "线程", link: "/线程" },
            { text: "线程池", link: "/线程池" },
          ],
        },
        { text: "锁", link: "/锁" },
        { text: "unsafe工具类", link: "/unsafe工具类" },
        { text: "locksupport", link: "/locksupport" },
        { text: "aqs", link: "/aqs" },
        { text: "Java8新特性", link: "/Java8新特性" },
        { text: "JUC2", link: "/JUC2" },
      ],
    },
    {
      text: "java虚拟机",
      base: "/02-java/java虚拟机",
      link: "/README",
      collapsed: false,
      items: [
        { text: "1. 概述", link: "/ch01-overview" },
        {
          text: "2. 前端编译阶段及字节码文件",
          link: "/ch02-compileandbytecode",
        },
        { text: "3. 类加载", link: "/ch03-classload" },
        { text: "4. 线程模型", link: "/ch04-threadmode" },
        { text: "5. 运行时内存结构", link: "/ch05-runtime" },
        { text: "6. 执行引擎", link: "/ch06-engine" },
        { text: "7. 垃圾回收理论", link: "/ch07-garbagecollection" },
        { text: "8. Hotspot 虚拟机 & 配置 Hotspot", link: "/ch08-hotspot" },
        { text: "9. 工具包", link: "/ch09-tools" },
        { text: "10. 调优", link: "/ch10-promote" },
        // { text: "11. 出错", link: "/锁" },
        // { text: "12. 停顿", link: "/锁" },
        // { text: "13. 参考", link: "/锁" },
      ],
    },
  ],

  "/03-工具和框架/工具": {
    text: "工具",
    base: "/03-工具和框架/工具",
    items: [
      { text: "Windows", link: "/windows" },
      { text: "Mac", link: "/mac" },
      { text: "CentOS", link: "/centos" },
      { text: "Vagrant", link: "/vagrant" },
      { text: "Docker", link: "/docker/README" },
      { text: "Git", link: "/git" },
      { text: "Maven", link: "/maven" },
      // { text: "Gradle", link: "/gradle" },
      // { text: "K8s", link: "/k8s" },
      // { text: "Jenkins", link: "/jenkins" },
      { text: "JDK", link: "/jdk" },
      { text: "IDEA", link: "/idea" },
      { text: "VSCode", link: "/vscode" },
    ],
  },
  "/03-工具和框架/框架": {
    text: "框架",
    base: "/03-工具和框架/框架",
    items: [
      // { text: "Mybatis", link: "/mybatis" },
      // { text: "Netty", link: "/netty" },
      {
        text: "Spring",
        base: "/03-工具和框架/框架/spring",
        link: "/README",
        items: [
          { text: "1. 背景", link: "/background" },
          { text: "2. Bean", link: "/bean" },
          { text: "3. 容器", link: "/container" },
          { text: "4. AOP", link: "/aop" },
          { text: "5. Web", link: "/web" },
          { text: "6. 事务", link: "/transaction" },
          { text: "7. 事件机制", link: "/event" },
          { text: "8. 应用上下文", link: "/applicationcontext" },
          // { text: "9. 资源操作", link: "" },
          // { text: "10. 高级特性", link: "" },
          // { text: "11. 数据校验", link: "" },
          // { text: "12. 国际化", link: "" },
          // { text: "13. 远程方法调用", link: "" },
          // { text: "14. 缓存操作", link: "" },
          // { text: "15. 测试", link: "" },
          { text: "16. AOT", link: "/aot" },
        ],
      },
      { text: "SpringMVC", link: "/springmvc" },
      { text: "SpringBoot", link: "/springboot" },
      {
        text: "SpringCloud",
        base: "/03-工具和框架/框架/springcloud",
        link: "/README",
        items: [
          { text: "Eureka", link: "/ch01-eureka" },
          { text: "Apollo", link: "/ch02-apollo" },
          { text: "Nacos 注册中心", link: "/ch03-nacos-register" },
          { text: "Nacos 配置中心", link: "/ch04-nacos-config" },
          { text: "OpenFeign", link: "/ch05-openfeign" },
          { text: "Gateway 网关", link: "/ch06-gateway" },
          { text: "sentinel", link: "/ch07-sentinel" },
          { text: "Seata", link: "/ch08-seata" },
          {
            text: "全局异常",
            link: "/ch99-appendix01-globalresponseandnacosexception",
          },
          { text: "依赖管理", link: "/ch99-appendix02-managedependence" },
          { text: "Saas 租户实战", link: "/ch99-appendix03-una_saas" },
          { text: "Logback 配置", link: "/ch99-appendix04-logback_xml" },
        ],
      },
      // { text: "Dubbo", link: "/dubbo" },
    ],
  },

  "/04-中间件/": {
    text: "中间件",
    base: "/04-中间件",
    items: [
      {
        text: "MySQL",
        base: "/04-中间件/mysql",
        link: "/README",
        items: [
          { text: "SQL", link: "/01-SQL" },
          { text: "架构与存储引擎", link: "/02-架构与存储引擎" },
          { text: "索引", link: "/03-索引" },
          { text: "隔离级别", link: "/04-隔离级别" },
          { text: "高可用与高性能", link: "/05-高可用与高性能" },
          { text: "实战", link: "/99-实战" },
          // { text: "SQL优化", link: "/SQL优化" },
          // { text: "MySQL集群", link: "/MySQL集群" },
        ],
      },
      {
        text: "Redis",
        base: "/04-中间件/redis",
        link: "/README",
        items: [
          { text: "Redis 对象系统", link: "/ch01-redisobj" },
          { text: "数据类型", link: "/ch02-datatype" },
          { text: "高级特性", link: "/ch03-greatfeature" },
          { text: "内存管理", link: "/ch04-memorymanage" },
          { text: "持久化机制", link: "/ch05-durationtodisk" },
          { text: "运行模式", link: "/ch06-running-mode" },
          { text: "产品运维", link: "/ch07-product-devops" },
          { text: "最佳实践", link: "/ch08-best-pratice" },
          {
            text: "缓存实战",
            link: "/ch09-appendix01-local-distribute-cache-pratice",
          },
          { text: "基准测试", link: "/ch09-appendix02-benchmark" },
        ],
      },
      { text: "MQ", link: "/mq" },
      { text: "ES", link: "/es" },
      { text: "Nginx", link: "/nginx" },
    ],
  },

  "/05-分布式/": {
    base: "/05-分布式",
    text: "分布式",
    link: "/README",
    items: [
      { text: "API", link: "/api" },
      { text: "分布式", link: "/distribution/README" },
      { text: "基础理论", link: "/distribution/theory" },
      { text: "分布式锁", link: "/lock/README" },
      { text: "分布式锁实践", link: "/lock/practice" },
      {
        text: "分布式事务",
        base: "/05-分布式/分布式事务",
        items: [
          { text: "基础理论", link: "/基础理论" },
          {
            text: "Seata实战",
            base: "/05-分布式/分布式事务/seata实战",
            items: [
              { text: "Seata的安装", link: "/安装" },
              {
                text: "Seata-AT模式",
                link: "/Seata-AT模式",
              },
              {
                text: "Seata-TCC模式",
                link: "/Seata-TCC模式",
              },
            ],
          },
        ],
      },
      { text: "分布式 ID", link: "/distribution/id" },
      { text: "分布式缓存", link: "/distribution/cache" },
      {
        text: "分布式消息",
        base: "/05-分布式/分布式消息",
        items: [
          { text: "基础理论", link: "/基础理论" },
          { text: "超详细RabbitMQ入门", link: "/超详细RabbitMQ入门" },
          { text: "RabbitMQ防止数据丢失", link: "/RabbitMQ防止数据丢失" },
          { text: "一文搞懂Kafka", link: "/一文搞懂Kafka" },
        ],
      },
      { text: "分布式存储（分库分表）", link: "/distribution/duration" },
      { text: "布式会话", link: "/distribution/session" },
      { text: "分布式 Job", link: "/distribution/job" },
    ],
  },

  "/06-软件质量管理/": {
    base: "/06-软件质量管理",
    link: "/README",
    text: "软件质量管理",
    items: [
      { text: "版本控制", link: "/use-cvs" },
      { text: "团队中任务的分配", link: "/split-task" },
      { text: "领域模型设计", link: "/DDD" },
      { text: "敏捷开发模型", link: "/crum" },
      { text: "服务器性能指标与基准测试", link: "/test" },
      { text: "设计一个系统", link: "/system-design" },
    ],
  },

  "/07-工程设计/": [
    {
      base: "/07-工程设计",
      text: "分布式",
      collapsed: false,
      items: [],
    },
  ],
  "/项目实战/": sourcecodeSidebar,
  "/网站维护/": websiteMaintainSidebar,
};
